/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Model.Mysql;
import java.awt.Color;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author sun
 */
public class GRNadvanced extends javax.swing.JPanel {

    String sup_id;
    Date from_date;
    Date to_date;

    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

    public void loadTable() {
        try {

            ResultSet rs = Mysql.search("SELECT `grn`.`id` AS `id`,`product`.`name` AS `name`,`grn_item`.`qty` AS `qty`,`grn_item`.`buying_price` AS `buying_price`,\n"
                    + "(`grn_item`.`qty`) *(`grn_item`.`buying_price`) AS `total`,`grn`.`date_time` AS `date_time`\n"
                    + " FROM `grn` INNER JOIN grn_item ON grn_item.grn_id=grn.id INNER JOIN stock ON grn_item.stock_id=stock.id\n"
                    + "INNER JOIN product ON product.id=stock.product_id");

            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);

            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString("id"));
                v.add(rs.getString("name"));
                v.add(rs.getString("qty"));
                v.add(rs.getString("buying_price"));
                v.add(rs.getString("total"));
                v.add(rs.getString("date_time"));
                dtm.addRow(v);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void loadTable(String query) {

        try {

            ResultSet rs = Mysql.search("SELECT `grn`.`id` AS `id`,`product`.`name` AS `name`,`grn_item`.`qty` AS `qty`,`grn_item`.`buying_price` AS `buying_price`,\n"
                    + "(`grn_item`.`qty`) *(`grn_item`.`buying_price`) AS `total`,`grn`.`date_time` AS `date_time`\n"
                    + " FROM `grn` INNER JOIN grn_item ON grn_item.grn_id=grn.id INNER JOIN stock ON grn_item.stock_id=stock.id\n"
                    + "INNER JOIN product ON product.id=stock.product_id " + query + "");

            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);

            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString("id"));
                v.add(rs.getString("name"));
                v.add(rs.getString("qty"));
                v.add(rs.getString("buying_price"));
                v.add(rs.getString("total"));
                v.add(rs.getString("date_time"));
                dtm.addRow(v);
            }

            if (jTable1.getRowCount() != 0) {
                jButton3.setEnabled(true);
            } else {
                jButton3.setEnabled(false);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * Creates new form GRNadvanced
     */
    public GRNadvanced() {
        initComponents();
        loadTable();
        
         jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setBackground(new Color(4, 98, 224));
        jTable1.getTableHeader().setForeground(Color.white);
        jTable1.setBackground(Color.WHITE);
        jTable1.setForeground(Color.BLACK);
        jTable1.setSelectionForeground(Color.WHITE);
        jTable1.setSelectionBackground(Color.RED);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(717, 493));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "GRN ID", "Product Name(Stock)", "Quantity", "Unit Price", "Total", "Date And Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setMinWidth(250);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(350);
            jTable1.getColumnModel().getColumn(2).setMinWidth(110);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(150);
            jTable1.getColumnModel().getColumn(3).setMinWidth(150);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(200);
            jTable1.getColumnModel().getColumn(4).setMinWidth(150);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(200);
            jTable1.getColumnModel().getColumn(5).setMinWidth(150);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(200);
        }

        jButton3.setBackground(new java.awt.Color(4, 98, 224));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Print Report");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        try {

            ResultSet rs = Mysql.search("SELECT `supplier`.`id`,`supplier`.`fname`,`supplier`.`lname`,`company`.`name` AS `company`,`city`.`name` AS `city`\n"
                    + " FROM `supplier` INNER JOIN `company` ON `company`.`id`=`supplier`.`company_id` INNER JOIN `company_branch`\n"
                    + "  ON `company_branch`.`id`=`supplier`.`company_branch_id` INNER JOIN `city`\n"
                    + "  ON `city`.`id`=`company_branch`.`city_id` WHERE `supplier`.`id`='" + sup_id + "' ");

            rs.next();

            InputStream stream = GRNbasic.class.getResourceAsStream("/reports/GRNSupplierItemHistory.jrxml");

            JasperReport jr = JasperCompileManager.compileReport(stream);

            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

            JRTableModelDataSource dataSource = new JRTableModelDataSource(dtm);

            HashMap parameters = new HashMap();
            parameters.put("id", rs.getString("id"));
            parameters.put("name", rs.getString("fname") + " " + rs.getString("lname"));
            parameters.put("company", rs.getString("company"));
            parameters.put("city", rs.getString("city"));

            String date_range;
            if (from_date != null && to_date != null) {
                date_range = sdf.format(from_date) + " TO " + sdf.format(to_date);
            } else if (from_date != null && to_date == null) {
                date_range = "From " + sdf.format(from_date);
            } else if (from_date == null && to_date != null) {
                date_range = "TO " + sdf.format(from_date);
            } else {
                date_range = "N/S";
            }

            parameters.put("range", date_range);

            JasperPrint jp = JasperFillManager.fillReport(jr, parameters, dataSource);

            JasperViewer.viewReport(jp, false);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
