/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Model.Mysql;
import java.awt.Color;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author sun
 */
public class GRNbasic extends javax.swing.JPanel {

    public void loadTable() {
        try {

            ResultSet rs = Mysql.search("SELECT `grn`.`id` AS `id`,`grn_payment`.`payment_amount` AS `amount`,`grn`.`date_time` FROM grn INNER JOIN grn_payment ON grn.id=grn_payment.grn_id");

            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);

            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString("id"));
                v.add(rs.getString("amount"));
                v.add(rs.getString("date_time"));
                dtm.addRow(v);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void loadTable(String query) {
        try {

            ResultSet rs = Mysql.search("SELECT `grn`.`id` AS `id`,`grn_payment`.`payment_amount` AS `amount`,`grn`.`date_time` FROM grn INNER JOIN grn_payment ON grn.id=grn_payment.grn_id " + query + "");

            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);

            int x = 0;
            while (rs.next()) {
                x = x + 1;
                Vector v = new Vector();
                v.add("#" + x);
                v.add(rs.getString("id"));
                v.add(rs.getString("amount"));
                v.add(rs.getString("date_time"));
                dtm.addRow(v);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * Creates new form GRNadvanced
     */
    public GRNbasic() {
        initComponents();
        loadTable();
        
         jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setBackground(new Color(4, 98, 224));
        jTable1.getTableHeader().setForeground(Color.white);
        jTable1.setBackground(Color.WHITE);
        jTable1.setForeground(Color.BLACK);
        jTable1.setSelectionForeground(Color.WHITE);
        jTable1.setSelectionBackground(Color.RED);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(717, 493));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "GRN ID", "Paid Total", "Issue Date And Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton3.setBackground(new java.awt.Color(4, 98, 224));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("View Report");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            String grn_id = jTable1.getValueAt(row, 0).toString();

            try {

                ResultSet rs = Mysql.search("SELECT `grn_payment`.`payment_amount`,`grn`.`date_time`,`supplier`.`id`,`supplier`.`fname`,`supplier`.`lname`,`company`.`name` AS `company`,`city`.`name` AS `city`\n"
                        + "   FROM `supplier` INNER JOIN `company` ON `company`.`id`=`supplier`.`company_id` INNER JOIN `company_branch`\n"
                        + "   ON `company_branch`.`id`=`supplier`.`company_branch_id` INNER JOIN `city`\n"
                        + "    ON `city`.`id`=`company_branch`.`city_id` INNER JOIN `grn` ON `grn`.`supplier_id`=`supplier`.`id` INNER JOIN `grn_payment` ON `grn_payment`.`grn_id`=`grn`.`id` WHERE `grn`.`id`='"+grn_id+"'");

                rs.next();
                
                InputStream stream = GRNbasic.class.getResourceAsStream("/reports/GRN.jrxml");

                JasperReport jr = JasperCompileManager.compileReport(stream);

                DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

                Connection dataSource = Mysql.getConnection();

                HashMap parameters = new HashMap();
                parameters.put("grn_id", grn_id);
                parameters.put("sup_id", rs.getString("id"));
                parameters.put("sup_name", rs.getString("fname")+" "+rs.getString("lname"));
                parameters.put("company", rs.getString("company"));
                parameters.put("city", rs.getString("city"));
                parameters.put("date", rs.getString("date_time"));
                parameters.put("amount", rs.getString("payment_amount"));
                        
                JasperPrint jp = JasperFillManager.fillReport(jr, parameters, dataSource);

                JasperViewer.viewReport(jp, false);

            } catch (Exception e) {
                e.printStackTrace();
            }

        }


    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
